### ISSUE TITLE
Build broken after #36

### ISSUE THREAD

**Issue by prestonvanloon** [multiformats/go-multiaddr-net#57]
#36 

multiformats/go-multiaddr-net/net.go:112:16: undefined: maConn

**Comment by prestonvanloon** [comment]
https://travis-ci.com/multiformats/go-multiaddr-net/jobs/224076640
