### PR TITLE
resolve #57 "Build broken after #36"

### LINKED ISSUE #57: Build broken after #36
#36 

multiformats/go-multiaddr-net/net.go:112:16: undefined: maConn

### PR DESCRIPTION
**Pull request by skillful-alex**
resolved #57 "Build broken after # 36"
build corrected

### CODE REVIEW

**Comment by Stebalien** [comment]
Thanks!
